#!/bin/bash

set -eu

if ! which go >/dev/null 2>&1; then
    echo "You need to install go."
    echo "Use brew or apt-get or whatever."
    exit 1
fi

if [[ -z "$GOPATH" ]]; then
    echo "Your \$GOPATH is not set, which is required for go to function."
    echo "Add 'export GOPATH=~/go' to your shell startup scripts."
    exit 1
fi

set -x

go get -t -u -d ./...
go get -u github.com/golang/lint/golint
go get -u github.com/rnubel/pgmgr

createuser --superuser cashew__app || true
pgmgr db create || true
pgmgr db migrate || true
